# Generated by Django 5.0.3 on 2024-03-28 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uaa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesaManagement',
            fields=[
                ('spends_uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount_spend', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('service_or_staff_spend', models.CharField(max_length=255)),
                ('reason_of_spend', models.TextField()),
                ('spend_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uaa.usersprofiles')),
            ],
            options={
                'db_table': 'pesa_management',
                'ordering': ['-spend_date'],
            },
        ),
    ]
