# Generated by Django 5.0.3 on 2024-03-28 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordRequestUsers',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('request_token', models.CharField(default=None, editable=False, max_length=300)),
                ('request_is_used', models.BooleanField(default=False)),
                ('request_is_active', models.BooleanField(default=True)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FORGOT PASSWORD REQUESTS',
                'db_table': 'pesa_users_forgot_password_request',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='UsersProfiles',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('user_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_phone', models.CharField(blank=True, default='', max_length=9000)),
                ('user_createddate', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USER PROFILES',
                'db_table': 'pesa_user_profiles',
                'ordering': ['-primary_key'],
            },
        ),
    ]
